/*
** aleffect-binding.cpp
**
** This file is part of Modshot.
*/

#include "binding-util.h"
#include "efx.h"
#include "efx-presets.h"
#include "al-util.h"

// helpers

#define ALEFFECT_DEFINE_INITIALIZER(type, identifier) \
	VALUE rb_aleffect_##type##_init(VALUE self) { \
		ALuint id; \
		alGenEffects(1, &id); \
		alEffecti(id, AL_EFFECT_TYPE, identifier); \
		rb_iv_set(self, "@handle", INT2NUM(id)); \
		return self; \
	}

#define ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(type, identifier, name) \
	VALUE rb_aleffect_##type##_get_##name(VALUE self) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle"));\
		float value = 0; \
		alGetEffectf(id, identifier, &value); \
		return DBL2NUM(value); \
	} \
	\
	VALUE rb_aleffect_##type##_set_##name(VALUE self, VALUE value) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle")); \
		float val = RFLOAT_VALUE(value); \
		alEffectf(id, identifier, val); \
		return Qnil; \
	}

#define ALEFFECT_DEFINE_ATTRIBUTE_INT(type, identifier, name) \
	VALUE rb_aleffect_##type##_get_##name(VALUE self) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle")); \
		int value = 0; \
		alGetEffecti(id, identifier, &value); \
		return INT2NUM(value); \
	} \
	\
	VALUE rb_aleffect_##type##_set_##name(VALUE self, VALUE value) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle")); \
		int val = NUM2INT(value); \
		alEffecti(id, identifier, val); \
		return Qnil; \
	}

#define ALEFFECT_DEFINE_ATTRIBUTE_FLOAT3(type, identifier, name) \
	VALUE rb_aleffect_##type##_get_##name(VALUE self) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle")); \
		float value[3] = {0, 0, 0}; \
		alGetEffectfv(id, identifier, value); \
		return rb_ary_new_from_args(3, DBL2NUM(value[0]), DBL2NUM(value[1]), DBL2NUM(value[2])); \
	} \
	\
	VALUE rb_aleffect_##type##_set_##name(VALUE self, VALUE value) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle")); \
		float val[3]; \
		val[0] = NUM2DBL(rb_ary_entry(value, 0)); \
		val[1] = NUM2DBL(rb_ary_entry(value, 1)); \
		val[2] = NUM2DBL(rb_ary_entry(value, 2)); \
		alEffectfv(id, identifier, val); \
		return Qnil; \
	}

#define ALEFFECT_CREATE_CLASS(type) \
	VALUE rb_c##type = rb_define_class_under(module, #type, rb_cObject); \
	rb_define_method(rb_c##type, "initialize", (VALUE(*)(...)) rb_aleffect_##type##_init, 0);

#define ALEFFECT_EXPOSE_ATTRIBUTE(type, name) \
	rb_define_method(rb_c##type, #name, (VALUE(*)(...)) rb_aleffect_##type##_get_##name, 0); \
	rb_define_method(rb_c##type, #name "=", (VALUE(*)(...)) rb_aleffect_##type##_set_##name, 1);

// EAXReverb
ALEFFECT_DEFINE_INITIALIZER(EAXReverb, AL_EFFECT_EAXREVERB)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_DENSITY, density)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_DIFFUSION, diffusion)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_GAIN, gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_GAINHF, gainhf)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_GAINLF, gainlf)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_DECAY_TIME, decay_time)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_DECAY_HFRATIO, decay_hfratio)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_DECAY_LFRATIO, decay_lfratio)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_REFLECTIONS_GAIN, reflections_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_REFLECTIONS_DELAY, reflections_delay)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT3(EAXReverb, AL_EAXREVERB_REFLECTIONS_PAN, reflections_pan)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_LATE_REVERB_GAIN, late_reverb_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_LATE_REVERB_DELAY, late_reverb_delay)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT3(EAXReverb, AL_EAXREVERB_LATE_REVERB_PAN, late_reverb_pan)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_ECHO_TIME, echo_time)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_ECHO_DEPTH, echo_depth)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_MODULATION_TIME, modulation_time)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_MODULATION_DEPTH, modulation_depth)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_AIR_ABSORPTION_GAINHF, air_absorption_gainhf)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_HFREFERENCE, hfreference)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_LFREFERENCE, lfreference)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(EAXReverb, AL_EAXREVERB_ROOM_ROLLOFF_FACTOR, room_rolloff_factor)
ALEFFECT_DEFINE_ATTRIBUTE_INT(EAXReverb, AL_EAXREVERB_DECAY_HFLIMIT, decay_hflimit)

// Reverb
ALEFFECT_DEFINE_INITIALIZER(Reverb, AL_EFFECT_REVERB)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_DENSITY, density)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_DIFFUSION, diffusion)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_GAIN, gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_GAINHF, gainhf)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_DECAY_TIME, decay_time)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_DECAY_HFRATIO, decay_hfratio)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_REFLECTIONS_GAIN, reflections_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_REFLECTIONS_DELAY, reflections_delay)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_LATE_REVERB_GAIN, late_reverb_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_LATE_REVERB_DELAY, late_reverb_delay)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_AIR_ABSORPTION_GAINHF, air_absorption_gainhf)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Reverb, AL_REVERB_ROOM_ROLLOFF_FACTOR, room_rolloff_factor)
ALEFFECT_DEFINE_ATTRIBUTE_INT(Reverb, AL_REVERB_DECAY_HFLIMIT, decay_hflimit)

// Chorus
ALEFFECT_DEFINE_INITIALIZER(Chorus, AL_EFFECT_CHORUS)
ALEFFECT_DEFINE_ATTRIBUTE_INT(Chorus, AL_CHORUS_WAVEFORM, waveform)
ALEFFECT_DEFINE_ATTRIBUTE_INT(Chorus, AL_CHORUS_PHASE, phase)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Chorus, AL_CHORUS_RATE, rate)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Chorus, AL_CHORUS_DEPTH, depth)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Chorus, AL_CHORUS_FEEDBACK, feedback)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Chorus, AL_CHORUS_DELAY, delay)

// Distortion
ALEFFECT_DEFINE_INITIALIZER(Distortion, AL_EFFECT_DISTORTION)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Distortion, AL_DISTORTION_EDGE, edge)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Distortion, AL_DISTORTION_GAIN, gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Distortion, AL_DISTORTION_LOWPASS_CUTOFF, lowpass_cutoff)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Distortion, AL_DISTORTION_EQCENTER, eqcenter)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Distortion, AL_DISTORTION_EQBANDWIDTH, eqbandwidth)

// Echo
ALEFFECT_DEFINE_INITIALIZER(Echo, AL_EFFECT_ECHO)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Echo, AL_ECHO_DELAY, delay)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Echo, AL_ECHO_LRDELAY, lrdelay)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Echo, AL_ECHO_DAMPING, damping)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Echo, AL_ECHO_FEEDBACK, feedback)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Echo, AL_ECHO_SPREAD, spread)

// Flanger
ALEFFECT_DEFINE_INITIALIZER(Flanger, AL_EFFECT_FLANGER)
ALEFFECT_DEFINE_ATTRIBUTE_INT(Flanger, AL_FLANGER_WAVEFORM, waveform)
ALEFFECT_DEFINE_ATTRIBUTE_INT(Flanger, AL_FLANGER_PHASE, phase)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Flanger, AL_FLANGER_RATE, rate)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Flanger, AL_FLANGER_DEPTH, depth)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Flanger, AL_FLANGER_FEEDBACK, feedback)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Flanger, AL_FLANGER_DELAY, delay)

// FrequencyShifter
ALEFFECT_DEFINE_INITIALIZER(FrequencyShifter, AL_EFFECT_FREQUENCY_SHIFTER)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(FrequencyShifter, AL_FREQUENCY_SHIFTER_FREQUENCY, frequency)
ALEFFECT_DEFINE_ATTRIBUTE_INT(FrequencyShifter, AL_FREQUENCY_SHIFTER_LEFT_DIRECTION, left_direction)
ALEFFECT_DEFINE_ATTRIBUTE_INT(FrequencyShifter, AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION, right_direction)

// VocalMorpher
ALEFFECT_DEFINE_INITIALIZER(VocalMorpher, AL_EFFECT_VOCAL_MORPHER)
ALEFFECT_DEFINE_ATTRIBUTE_INT(VocalMorpher, AL_VOCAL_MORPHER_PHONEMEA, phoneme_a)
ALEFFECT_DEFINE_ATTRIBUTE_INT(VocalMorpher, AL_VOCAL_MORPHER_PHONEMEB, phoneme_b)
ALEFFECT_DEFINE_ATTRIBUTE_INT(VocalMorpher, AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING, phoneme_a_coarse_tuning)
ALEFFECT_DEFINE_ATTRIBUTE_INT(VocalMorpher, AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING, phoneme_b_coarse_tuning)
ALEFFECT_DEFINE_ATTRIBUTE_INT(VocalMorpher, AL_VOCAL_MORPHER_WAVEFORM, waveform)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(VocalMorpher, AL_VOCAL_MORPHER_RATE, rate)

// PitchShifter
ALEFFECT_DEFINE_INITIALIZER(PitchShifter, AL_EFFECT_PITCH_SHIFTER)
ALEFFECT_DEFINE_ATTRIBUTE_INT(PitchShifter, AL_PITCH_SHIFTER_COARSE_TUNE, coarse_tune)
ALEFFECT_DEFINE_ATTRIBUTE_INT(PitchShifter, AL_PITCH_SHIFTER_FINE_TUNE, fine_tune)

// RingModulator
ALEFFECT_DEFINE_INITIALIZER(RingModulator, AL_EFFECT_RING_MODULATOR)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(RingModulator, AL_RING_MODULATOR_FREQUENCY, frequency)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(RingModulator, AL_RING_MODULATOR_HIGHPASS_CUTOFF, highpass_cutoff)
ALEFFECT_DEFINE_ATTRIBUTE_INT(RingModulator, AL_RING_MODULATOR_WAVEFORM, waveform)

// AutoWah
ALEFFECT_DEFINE_INITIALIZER(AutoWah, AL_EFFECT_AUTOWAH)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(AutoWah, AL_AUTOWAH_ATTACK_TIME, attack_time)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(AutoWah, AL_AUTOWAH_RELEASE_TIME, release_time)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(AutoWah, AL_AUTOWAH_RESONANCE, resonance)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(AutoWah, AL_AUTOWAH_PEAK_GAIN, peak_gain)

// Compressor
ALEFFECT_DEFINE_INITIALIZER(Compressor, AL_EFFECT_COMPRESSOR)
ALEFFECT_DEFINE_ATTRIBUTE_INT(Compressor, AL_COMPRESSOR_ONOFF, onoff)

// Equalizer
ALEFFECT_DEFINE_INITIALIZER(Equalizer, AL_EFFECT_EQUALIZER)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_LOW_GAIN, low_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_LOW_CUTOFF, low_cutoff)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_MID1_GAIN, mid1_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_MID1_CENTER, mid1_center)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_MID1_WIDTH, mid1_width)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_MID2_GAIN, mid2_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_MID2_CENTER, mid2_center)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_MID2_WIDTH, mid2_width)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_HIGH_GAIN, high_gain)
ALEFFECT_DEFINE_ATTRIBUTE_FLOAT(Equalizer, AL_EQUALIZER_HIGH_CUTOFF, high_cutoff)

// EAXReverb Presets
#define ALEFFECT_DEFINE_PRESET(preset, name) \
	VALUE rb_aleffect_EAXReverb_load_preset_##name(VALUE self) { \
		ALuint id = NUM2INT(rb_iv_get(self, "@handle")); \
		EFXEAXREVERBPROPERTIES properties = preset; \
		alEffectf(id, AL_EAXREVERB_DENSITY, properties.flDensity); \
		alEffectf(id, AL_EAXREVERB_DIFFUSION, properties.flDiffusion); \
		alEffectf(id, AL_EAXREVERB_GAIN, properties.flGain); \
		alEffectf(id, AL_EAXREVERB_GAINHF, properties.flGainHF); \
		alEffectf(id, AL_EAXREVERB_GAINLF, properties.flGainLF); \
		alEffectf(id, AL_EAXREVERB_DECAY_TIME, properties.flDecayTime); \
		alEffectf(id, AL_EAXREVERB_DECAY_HFRATIO, properties.flDecayHFRatio); \
		alEffectf(id, AL_EAXREVERB_DECAY_LFRATIO, properties.flDecayLFRatio); \
		alEffectf(id, AL_EAXREVERB_REFLECTIONS_GAIN, properties.flReflectionsGain); \
		alEffectf(id, AL_EAXREVERB_REFLECTIONS_DELAY, properties.flReflectionsDelay); \
		alEffectfv(id, AL_EAXREVERB_REFLECTIONS_PAN, properties.flReflectionsPan); \
		alEffectf(id, AL_EAXREVERB_LATE_REVERB_GAIN, properties.flLateReverbGain); \
		alEffectf(id, AL_EAXREVERB_LATE_REVERB_DELAY, properties.flLateReverbDelay); \
		alEffectfv(id, AL_EAXREVERB_LATE_REVERB_PAN, properties.flLateReverbPan); \
		alEffectf(id, AL_EAXREVERB_ECHO_TIME, properties.flEchoTime); \
		alEffectf(id, AL_EAXREVERB_ECHO_DEPTH, properties.flEchoDepth); \
		alEffectf(id, AL_EAXREVERB_MODULATION_TIME, properties.flModulationTime); \
		alEffectf(id, AL_EAXREVERB_MODULATION_DEPTH, properties.flModulationDepth); \
		alEffectf(id, AL_EAXREVERB_AIR_ABSORPTION_GAINHF, properties.flAirAbsorptionGainHF); \
		alEffectf(id, AL_EAXREVERB_HFREFERENCE, properties.flHFReference); \
		alEffectf(id, AL_EAXREVERB_LFREFERENCE, properties.flLFReference); \
		alEffectf(id, AL_EAXREVERB_ROOM_ROLLOFF_FACTOR, properties.flRoomRolloffFactor); \
		alEffecti(id, AL_EAXREVERB_DECAY_HFLIMIT, properties.iDecayHFLimit); \
		return Qnil; \
	}

#define ALEFFECT_EXPOSE_PRESET(name) \
	rb_define_method(rb_cEAXReverb, "load_preset_" #name, (VALUE(*)(...)) rb_aleffect_EAXReverb_load_preset_##name, 0);

ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_GENERIC, generic)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PADDEDCELL, paddedcell)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ROOM, room)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_BATHROOM, bathroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_LIVINGROOM, livingroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_STONEROOM, stoneroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_AUDITORIUM, auditorium)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CONCERTHALL, concerthall)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CAVE, cave)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ARENA, arena)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_HANGAR, hangar)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CARPETEDHALLWAY, carpetedhallway)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_HALLWAY, hallway)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_STONECORRIDOR, stonecorridor)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ALLEY, alley)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FOREST, forest)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY, city)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_MOUNTAINS, mountains)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_QUARRY, quarry)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PLAIN, plain)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PARKINGLOT, parkinglot)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SEWERPIPE, sewerpipe)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_UNDERWATER, underwater)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRUGGED, drugged)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DIZZY, dizzy)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PSYCHOTIC, psychotic)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_SMALLROOM, castle_smallroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_SHORTPASSAGE, castle_shortpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_MEDIUMROOM, castle_mediumroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_LARGEROOM, castle_largeroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_LONGPASSAGE, castle_longpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_HALL, castle_hall)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_CUPBOARD, castle_cupboard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_COURTYARD, castle_courtyard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CASTLE_ALCOVE, castle_alcove)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_SMALLROOM, factory_smallroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_SHORTPASSAGE, factory_shortpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_MEDIUMROOM, factory_mediumroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_LARGEROOM, factory_largeroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_LONGPASSAGE, factory_longpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_HALL, factory_hall)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_CUPBOARD, factory_cupboard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_COURTYARD, factory_courtyard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_FACTORY_ALCOVE, factory_alcove)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_SMALLROOM, icepalace_smallroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_SHORTPASSAGE, icepalace_shortpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_MEDIUMROOM, icepalace_mediumroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_LARGEROOM, icepalace_largeroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_LONGPASSAGE, icepalace_longpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_HALL, icepalace_hall)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_CUPBOARD, icepalace_cupboard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_COURTYARD, icepalace_courtyard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_ICEPALACE_ALCOVE, icepalace_alcove)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_SMALLROOM, spacestation_smallroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_SHORTPASSAGE, spacestation_shortpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_MEDIUMROOM, spacestation_mediumroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_LARGEROOM, spacestation_largeroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_LONGPASSAGE, spacestation_longpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_HALL, spacestation_hall)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_CUPBOARD, spacestation_cupboard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPACESTATION_ALCOVE, spacestation_alcove)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_SMALLROOM, wooden_smallroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_SHORTPASSAGE, wooden_shortpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_MEDIUMROOM, wooden_mediumroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_LARGEROOM, wooden_largeroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_LONGPASSAGE, wooden_longpassage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_HALL, wooden_hall)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_CUPBOARD, wooden_cupboard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_COURTYARD, wooden_courtyard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_WOODEN_ALCOVE, wooden_alcove)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_EMPTYSTADIUM, sport_emptystadium)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_SQUASHCOURT, sport_squashcourt)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_SMALLSWIMMINGPOOL, sport_smallswimmingpool)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_LARGESWIMMINGPOOL, sport_largeswimmingpool)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_GYMNASIUM, sport_gymnasium)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_FULLSTADIUM, sport_fullstadium)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SPORT_STADIUMTANNOY, sport_stadiumtannoy)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PREFAB_WORKSHOP, prefab_workshop)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PREFAB_SCHOOLROOM, prefab_schoolroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PREFAB_PRACTISEROOM, prefab_practiseroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PREFAB_OUTHOUSE, prefab_outhouse)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PREFAB_CARAVAN, prefab_caravan)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DOME_TOMB, dome_tomb)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PIPE_SMALL, pipe_small)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DOME_SAINTPAULS, dome_saintpauls)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PIPE_LONGTHIN, pipe_longthin)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PIPE_LARGE, pipe_large)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_PIPE_RESONANT, pipe_resonant)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_OUTDOORS_BACKYARD, outdoors_backyard)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_OUTDOORS_ROLLINGPLAINS, outdoors_rollingplains)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_OUTDOORS_DEEPCANYON, outdoors_deepcanyon)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_OUTDOORS_CREEK, outdoors_creek)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_OUTDOORS_VALLEY, outdoors_valley)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_MOOD_HEAVEN, mood_heaven)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_MOOD_HELL, mood_hell)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_MOOD_MEMORY, mood_memory)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_COMMENTATOR, driving_commentator)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_PITGARAGE, driving_pitgarage)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_INCAR_RACER, driving_incar_racer)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_INCAR_SPORTS, driving_incar_sports)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_INCAR_LUXURY, driving_incar_luxury)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_FULLGRANDSTAND, driving_fullgrandstand)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_EMPTYGRANDSTAND, driving_emptygrandstand)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DRIVING_TUNNEL, driving_tunnel)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY_STREETS, city_streets)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY_SUBWAY, city_subway)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY_MUSEUM, city_museum)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY_LIBRARY, city_library)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY_UNDERPASS, city_underpass)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CITY_ABANDONED, city_abandoned)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_DUSTYROOM, dustyroom)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_CHAPEL, chapel)
ALEFFECT_DEFINE_PRESET(EFX_REVERB_PRESET_SMALLWATERROOM, smallwaterroom)

void aleffectBindingInit()
{
	VALUE module = rb_define_module("ALEffect");

	ALEFFECT_CREATE_CLASS(EAXReverb)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, density)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, diffusion)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, gainhf)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, gainlf)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, decay_time)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, decay_hfratio)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, decay_lfratio)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, reflections_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, reflections_delay)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, reflections_pan)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, late_reverb_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, late_reverb_delay)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, late_reverb_pan)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, echo_time)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, echo_depth)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, modulation_time)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, modulation_depth)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, air_absorption_gainhf)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, hfreference)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, lfreference)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, room_rolloff_factor)
	ALEFFECT_EXPOSE_ATTRIBUTE(EAXReverb, decay_hflimit)

	ALEFFECT_EXPOSE_PRESET(generic)
	ALEFFECT_EXPOSE_PRESET(paddedcell)
	ALEFFECT_EXPOSE_PRESET(room)
	ALEFFECT_EXPOSE_PRESET(bathroom)
	ALEFFECT_EXPOSE_PRESET(livingroom)
	ALEFFECT_EXPOSE_PRESET(stoneroom)
	ALEFFECT_EXPOSE_PRESET(auditorium)
	ALEFFECT_EXPOSE_PRESET(concerthall)
	ALEFFECT_EXPOSE_PRESET(cave)
	ALEFFECT_EXPOSE_PRESET(arena)
	ALEFFECT_EXPOSE_PRESET(hangar)
	ALEFFECT_EXPOSE_PRESET(carpetedhallway)
	ALEFFECT_EXPOSE_PRESET(hallway)
	ALEFFECT_EXPOSE_PRESET(stonecorridor)
	ALEFFECT_EXPOSE_PRESET(alley)
	ALEFFECT_EXPOSE_PRESET(forest)
	ALEFFECT_EXPOSE_PRESET(city)
	ALEFFECT_EXPOSE_PRESET(mountains)
	ALEFFECT_EXPOSE_PRESET(quarry)
	ALEFFECT_EXPOSE_PRESET(plain)
	ALEFFECT_EXPOSE_PRESET(parkinglot)
	ALEFFECT_EXPOSE_PRESET(sewerpipe)
	ALEFFECT_EXPOSE_PRESET(underwater)
	ALEFFECT_EXPOSE_PRESET(drugged)
	ALEFFECT_EXPOSE_PRESET(dizzy)
	ALEFFECT_EXPOSE_PRESET(psychotic)
	ALEFFECT_EXPOSE_PRESET(castle_smallroom)
	ALEFFECT_EXPOSE_PRESET(castle_shortpassage)
	ALEFFECT_EXPOSE_PRESET(castle_mediumroom)
	ALEFFECT_EXPOSE_PRESET(castle_largeroom)
	ALEFFECT_EXPOSE_PRESET(castle_longpassage)
	ALEFFECT_EXPOSE_PRESET(castle_hall)
	ALEFFECT_EXPOSE_PRESET(castle_cupboard)
	ALEFFECT_EXPOSE_PRESET(castle_courtyard)
	ALEFFECT_EXPOSE_PRESET(castle_alcove)
	ALEFFECT_EXPOSE_PRESET(factory_smallroom)
	ALEFFECT_EXPOSE_PRESET(factory_shortpassage)
	ALEFFECT_EXPOSE_PRESET(factory_mediumroom)
	ALEFFECT_EXPOSE_PRESET(factory_largeroom)
	ALEFFECT_EXPOSE_PRESET(factory_longpassage)
	ALEFFECT_EXPOSE_PRESET(factory_hall)
	ALEFFECT_EXPOSE_PRESET(factory_cupboard)
	ALEFFECT_EXPOSE_PRESET(factory_courtyard)
	ALEFFECT_EXPOSE_PRESET(factory_alcove)
	ALEFFECT_EXPOSE_PRESET(icepalace_smallroom)
	ALEFFECT_EXPOSE_PRESET(icepalace_shortpassage)
	ALEFFECT_EXPOSE_PRESET(icepalace_mediumroom)
	ALEFFECT_EXPOSE_PRESET(icepalace_largeroom)
	ALEFFECT_EXPOSE_PRESET(icepalace_longpassage)
	ALEFFECT_EXPOSE_PRESET(icepalace_hall)
	ALEFFECT_EXPOSE_PRESET(icepalace_cupboard)
	ALEFFECT_EXPOSE_PRESET(icepalace_courtyard)
	ALEFFECT_EXPOSE_PRESET(icepalace_alcove)
	ALEFFECT_EXPOSE_PRESET(spacestation_smallroom)
	ALEFFECT_EXPOSE_PRESET(spacestation_shortpassage)
	ALEFFECT_EXPOSE_PRESET(spacestation_mediumroom)
	ALEFFECT_EXPOSE_PRESET(spacestation_largeroom)
	ALEFFECT_EXPOSE_PRESET(spacestation_longpassage)
	ALEFFECT_EXPOSE_PRESET(spacestation_hall)
	ALEFFECT_EXPOSE_PRESET(spacestation_cupboard)
	ALEFFECT_EXPOSE_PRESET(spacestation_alcove)
	ALEFFECT_EXPOSE_PRESET(wooden_smallroom)
	ALEFFECT_EXPOSE_PRESET(wooden_shortpassage)
	ALEFFECT_EXPOSE_PRESET(wooden_mediumroom)
	ALEFFECT_EXPOSE_PRESET(wooden_largeroom)
	ALEFFECT_EXPOSE_PRESET(wooden_longpassage)
	ALEFFECT_EXPOSE_PRESET(wooden_hall)
	ALEFFECT_EXPOSE_PRESET(wooden_cupboard)
	ALEFFECT_EXPOSE_PRESET(wooden_courtyard)
	ALEFFECT_EXPOSE_PRESET(wooden_alcove)
	ALEFFECT_EXPOSE_PRESET(sport_emptystadium)
	ALEFFECT_EXPOSE_PRESET(sport_squashcourt)
	ALEFFECT_EXPOSE_PRESET(sport_smallswimmingpool)
	ALEFFECT_EXPOSE_PRESET(sport_largeswimmingpool)
	ALEFFECT_EXPOSE_PRESET(sport_gymnasium)
	ALEFFECT_EXPOSE_PRESET(sport_fullstadium)
	ALEFFECT_EXPOSE_PRESET(sport_stadiumtannoy)
	ALEFFECT_EXPOSE_PRESET(prefab_workshop)
	ALEFFECT_EXPOSE_PRESET(prefab_schoolroom)
	ALEFFECT_EXPOSE_PRESET(prefab_practiseroom)
	ALEFFECT_EXPOSE_PRESET(prefab_outhouse)
	ALEFFECT_EXPOSE_PRESET(prefab_caravan)
	ALEFFECT_EXPOSE_PRESET(dome_tomb)
	ALEFFECT_EXPOSE_PRESET(pipe_small)
	ALEFFECT_EXPOSE_PRESET(dome_saintpauls)
	ALEFFECT_EXPOSE_PRESET(pipe_longthin)
	ALEFFECT_EXPOSE_PRESET(pipe_large)
	ALEFFECT_EXPOSE_PRESET(pipe_resonant)
	ALEFFECT_EXPOSE_PRESET(outdoors_backyard)
	ALEFFECT_EXPOSE_PRESET(outdoors_rollingplains)
	ALEFFECT_EXPOSE_PRESET(outdoors_deepcanyon)
	ALEFFECT_EXPOSE_PRESET(outdoors_creek)
	ALEFFECT_EXPOSE_PRESET(outdoors_valley)
	ALEFFECT_EXPOSE_PRESET(mood_heaven)
	ALEFFECT_EXPOSE_PRESET(mood_hell)
	ALEFFECT_EXPOSE_PRESET(mood_memory)
	ALEFFECT_EXPOSE_PRESET(driving_commentator)
	ALEFFECT_EXPOSE_PRESET(driving_pitgarage)
	ALEFFECT_EXPOSE_PRESET(driving_incar_racer)
	ALEFFECT_EXPOSE_PRESET(driving_incar_sports)
	ALEFFECT_EXPOSE_PRESET(driving_incar_luxury)
	ALEFFECT_EXPOSE_PRESET(driving_fullgrandstand)
	ALEFFECT_EXPOSE_PRESET(driving_emptygrandstand)
	ALEFFECT_EXPOSE_PRESET(driving_tunnel)
	ALEFFECT_EXPOSE_PRESET(city_streets)
	ALEFFECT_EXPOSE_PRESET(city_subway)
	ALEFFECT_EXPOSE_PRESET(city_museum)
	ALEFFECT_EXPOSE_PRESET(city_library)
	ALEFFECT_EXPOSE_PRESET(city_underpass)
	ALEFFECT_EXPOSE_PRESET(city_abandoned)
	ALEFFECT_EXPOSE_PRESET(dustyroom)
	ALEFFECT_EXPOSE_PRESET(chapel)
	ALEFFECT_EXPOSE_PRESET(smallwaterroom)

	ALEFFECT_CREATE_CLASS(Reverb)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, density)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, diffusion)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, gainhf)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, decay_time)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, decay_hfratio)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, reflections_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, reflections_delay)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, late_reverb_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, late_reverb_delay)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, air_absorption_gainhf)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, room_rolloff_factor)
	ALEFFECT_EXPOSE_ATTRIBUTE(Reverb, decay_hflimit)

	ALEFFECT_CREATE_CLASS(Chorus)
	ALEFFECT_EXPOSE_ATTRIBUTE(Chorus, waveform)
	ALEFFECT_EXPOSE_ATTRIBUTE(Chorus, phase)
	ALEFFECT_EXPOSE_ATTRIBUTE(Chorus, rate)
	ALEFFECT_EXPOSE_ATTRIBUTE(Chorus, depth)
	ALEFFECT_EXPOSE_ATTRIBUTE(Chorus, feedback)
	ALEFFECT_EXPOSE_ATTRIBUTE(Chorus, delay)

	ALEFFECT_CREATE_CLASS(Distortion)
	ALEFFECT_EXPOSE_ATTRIBUTE(Distortion, edge)
	ALEFFECT_EXPOSE_ATTRIBUTE(Distortion, gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Distortion, lowpass_cutoff)
	ALEFFECT_EXPOSE_ATTRIBUTE(Distortion, eqcenter)
	ALEFFECT_EXPOSE_ATTRIBUTE(Distortion, eqbandwidth)

	ALEFFECT_CREATE_CLASS(Echo)
	ALEFFECT_EXPOSE_ATTRIBUTE(Echo, delay)
	ALEFFECT_EXPOSE_ATTRIBUTE(Echo, lrdelay)
	ALEFFECT_EXPOSE_ATTRIBUTE(Echo, damping)
	ALEFFECT_EXPOSE_ATTRIBUTE(Echo, feedback)
	ALEFFECT_EXPOSE_ATTRIBUTE(Echo, spread)

	ALEFFECT_CREATE_CLASS(Flanger)
	ALEFFECT_EXPOSE_ATTRIBUTE(Flanger, waveform)
	ALEFFECT_EXPOSE_ATTRIBUTE(Flanger, phase)
	ALEFFECT_EXPOSE_ATTRIBUTE(Flanger, rate)
	ALEFFECT_EXPOSE_ATTRIBUTE(Flanger, depth)
	ALEFFECT_EXPOSE_ATTRIBUTE(Flanger, feedback)
	ALEFFECT_EXPOSE_ATTRIBUTE(Flanger, delay)

	ALEFFECT_CREATE_CLASS(FrequencyShifter)
	ALEFFECT_EXPOSE_ATTRIBUTE(FrequencyShifter, frequency)
	ALEFFECT_EXPOSE_ATTRIBUTE(FrequencyShifter, left_direction)
	ALEFFECT_EXPOSE_ATTRIBUTE(FrequencyShifter, right_direction)

	ALEFFECT_CREATE_CLASS(VocalMorpher)
	ALEFFECT_EXPOSE_ATTRIBUTE(VocalMorpher, phoneme_a)
	ALEFFECT_EXPOSE_ATTRIBUTE(VocalMorpher, phoneme_b)
	ALEFFECT_EXPOSE_ATTRIBUTE(VocalMorpher, phoneme_a_coarse_tuning)
	ALEFFECT_EXPOSE_ATTRIBUTE(VocalMorpher, phoneme_b_coarse_tuning)
	ALEFFECT_EXPOSE_ATTRIBUTE(VocalMorpher, waveform)
	ALEFFECT_EXPOSE_ATTRIBUTE(VocalMorpher, rate)

	ALEFFECT_CREATE_CLASS(PitchShifter)
	ALEFFECT_EXPOSE_ATTRIBUTE(PitchShifter, coarse_tune)
	ALEFFECT_EXPOSE_ATTRIBUTE(PitchShifter, fine_tune)

	ALEFFECT_CREATE_CLASS(RingModulator)
	ALEFFECT_EXPOSE_ATTRIBUTE(RingModulator, frequency)
	ALEFFECT_EXPOSE_ATTRIBUTE(RingModulator, highpass_cutoff)
	ALEFFECT_EXPOSE_ATTRIBUTE(RingModulator, waveform)

	ALEFFECT_CREATE_CLASS(AutoWah)
	ALEFFECT_EXPOSE_ATTRIBUTE(AutoWah, attack_time)
	ALEFFECT_EXPOSE_ATTRIBUTE(AutoWah, release_time)
	ALEFFECT_EXPOSE_ATTRIBUTE(AutoWah, resonance)
	ALEFFECT_EXPOSE_ATTRIBUTE(AutoWah, peak_gain)

	ALEFFECT_CREATE_CLASS(Compressor)
	ALEFFECT_EXPOSE_ATTRIBUTE(Compressor, onoff)

	ALEFFECT_CREATE_CLASS(Equalizer)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, low_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, low_cutoff)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, mid1_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, mid1_center)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, mid1_width)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, mid2_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, mid2_center)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, mid2_width)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, high_gain)
	ALEFFECT_EXPOSE_ATTRIBUTE(Equalizer, high_cutoff)

}
